language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
before_install:
  - sudo apt-get update -qq
  - if test $CC = gcc; then sudo apt-get install --yes --force-yes gcc-4.7 g++-4.7; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 20; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 20; fi
  - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
  - if test $CC = gcc; then sudo update-alternatives --config g++; fi
  - sudo apt-get install --yes --force-yes cmake cmake-data

script: ./scripts/travis.sh
