version: 1.0.{build}
image: Visual Studio 2015 CTP 6
install:
- git submodule update --init --recursive
build_script:
- cmd: |-
    python project_generation_scripts.py --generate-tests --all-platforms
    generate_solution_scripts/win32/debug-01-generate.bat
    cd "projects/win32-debug"
    cmake --build . --target ALL_BUILD --config Debug
    cmake --build . --target RUN_TESTS --config Debug
